#!/usr/bin/expect -f
#
# This Expect script was generated by autoexpect on Sun Mar 13 17:28:33 2016
# Expect and autoexpect were both written by Don Libes, NIST.
#
# Note that autoexpect does not guarantee a working script.  It
# necessarily has to guess about certain things.  Two reasons a script
# might fail are:
#
# 1) timing - A surprising number of programs (rn, ksh, zsh, telnet,
# etc.) and devices discard or ignore keystrokes that arrive "too
# quickly" after prompts.  If you find your new script hanging up at
# one spot, try adding a short sleep just before the previous send.
# Setting "force_conservative" to 1 (see below) makes Expect do this
# automatically - pausing briefly before sending each character.  This
# pacifies every program I know of.  The -c flag makes the script do
# this in the first place.  The -C flag allows you to define a
# character to toggle this mode off and on.

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

#
# 2) differing output - Some programs produce different output each time
# they run.  The "date" command is an obvious example.  Another is
# ftp, if it produces throughput statistics at the end of a file
# transfer.  If this causes a problem, delete these patterns or replace
# them with wildcards.  An alternative is to use the -p flag (for
# "prompt") which makes Expect only look for the last line of output
# (i.e., the prompt).  The -P flag allows you to define a character to
# toggle this mode off and on.
#
# Read the man page for more info.
#
# -Don


set timeout -1
spawn $env(SHELL)
match_max 100000

# Gen-revoke master key
expect  "\$"
send -- "gpg2 --no-permission-warning --output keys/master-revocation.asc --gen-revoke MASTER"
expect  "gpg2 --no-permission-warning --output keys/master-revocation.asc --gen-revoke MASTER"
send -- "\r"
expect  "Create a revocation certificate for this key? (y/N) "
send -- "y\r"
expect  "Your decision? "
send -- "3\r"
expect  "> "
send -- "Used revocation certificate from initial key creation. It's likely that I have lost access to this private key.\r"
expect  "> "
send -- "\r"
expect  "Is this okay? (y/N) "
send -- "y\r"

# Gen-revoke signing subkey
expect  "\$"
send -- "gpg2 --no-permission-warning --output keys/sign-subkey-revocation.asc --gen-revoke SIGNKEY"
expect  "gpg2 --no-permission-warning --output keys/sign-subkey-revocation.asc --gen-revoke SIGNKEY"
send -- "\r"
expect  "Create a revocation certificate for this key? (y/N) "
send -- "y\r"
expect  "Your decision? "
send -- "3\r"
expect  "> "
send -- "Used revocation certificate from initial key creation. It's likely that I have lost access to this private key.\r"
expect  "> "
send -- "\r"
expect  "Is this okay? (y/N) "
send -- "y\r"

# Gen-revoke authentication subkey
expect  "\$"
send -- "gpg2 --no-permission-warning --output keys/auth-subkey-revocation.asc --gen-revoke AUTHKEY"
expect  "gpg2 --no-permission-warning --output keys/auth-subkey-revocation.asc --gen-revoke AUTHKEY"
send -- "\r"
expect  "Create a revocation certificate for this key? (y/N) "
send -- "y\r"
expect  "Your decision? "
send -- "3\r"
expect  "> "
send -- "Used revocation certificate from initial key creation. It's likely that I have lost access to this private key.\r"
expect  "> "
send -- "\r"
expect  "Is this okay? (y/N) "
send -- "y\r"

# Gen-revoke encryption subkey
expect  "\$"
send -- "gpg2 --no-permission-warning --output keys/encryption-subkey-revocation.asc --gen-revoke ENCRKEY"
expect  "gpg2 --no-permission-warning --output keys/encryption-subkey-revocation.asc --gen-revoke ENCRKEY"
send -- "\r"
expect  "Create a revocation certificate for this key? (y/N) "
send -- "y\r"
expect  "Your decision? "
send -- "3\r"
expect  "> "
send -- "Used revocation certificate from initial key creation. It's likely that I have lost access to this private key.\r"
expect  "> "
send -- "\r"
expect  "Is this okay? (y/N) "
send -- "y\r"

#expect  "\$"
sleep 0.25
send -- ""
expect eof
